### ISSUE TITLE
Getting SSL issue in this code.

### ISSUE THREAD

**Issue by ga3003** [AH72KING/Instagram-scraping#1]
I have used this code previously in my project and it was working fine that time. But now I am trying to use it in another project, but its not workng and showing the error **file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages**.

I have tried to remove this error by using your code with below changes:
```
$arrContextOptions=array(
				"ssl"=>array(
						"verify_peer"=>false
				),
		);
		
		$insta_source = file_get_contents('https://www.instagram.com/explore/tags/'.$tag.'/', false, stream_context_create($arrContextOptions));
		$shards = explode('window._sharedData = ', $insta_source);
		$insta_json = explode(';</script>', $shards[1]);
		$insta_array = json_decode($insta_json[0], TRUE);
		print_r($insta_array);
		return $insta_array;
```

If you can help me to solve this problem, let me know.

**Comment by AH72KING** [comment]
try this

` 'verify_peer' => false,
   'verify_peer_name' => false,`

or use Curl 
it will be better than "file_get_contents"

**Comment by AH72KING** [comment]
I am closing it
if issue still there let me know please
