### ISSUE TITLE
instagram_user_images.php

### ISSUE THREAD

**Issue by arwivi1903** [AH72KING/Instagram-scraping#3]
Hello there.

I can pull data with your "tag" codes. Data is not coming with your "user" codes. I just changed "username". how can you help?

username = '**teknikservis.club'**;

**Comment by AH72KING** [comment]
Hi @arwivi1903 have you changed something in code ?
this two years old code is still working for me 
I used your username = 'teknikservis.club'

![Capture1](https://user-images.githubusercontent.com/8464289/85923795-93fb7180-b8a7-11ea-8a03-969b1f1dec6b.PNG)
![Capture2](https://user-images.githubusercontent.com/8464289/85923799-99f15280-b8a7-11ea-949c-bb2c4a9490d8.PNG)

**Comment by AH72KING** [comment]
I tried my local server to run the script 
using laragon for it

**Comment by arwivi1903** [comment]
I do not understand what you're talking about.

iPhone’umdan gönderildi

> Ahsan Khan <notifications@github.com> şunları yazdı (27 Haz 2020 16:55):
> 
> I tried my local server to run the script
> using laragon for it

**Comment by AH72KING** [comment]
> I do not understand what you're talking about. iPhone’umdan gönderildi
> […](#)
> Ahsan Khan ***@***.***> şunları yazdı (27 Haz 2020 16:55): I tried my local server to run the script using laragon for it

You said 
"I can pull data with your "tag" codes. Data is not coming with your "user" codes. I just changed "username". how can you help?

username = 'teknikservis.club';"

but tried its working
